# Generated by Django 4.1.2 on 2022-11-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=70, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Пост')),
            ],
        ),
    ]
