# Generated by Django 4.1.2 on 2022-12-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_options_alter_user_profile_pic_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='author',
        ),
    ]
