# Generated by Django 4.1.2 on 2023-01-23 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_create_time_post_parent_theme_post_post_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
        ),
        migrations.AddField(
            model_name='theme',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent_theme',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main.theme'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(blank=True, upload_to='communication_pictures/posts/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='media',
            field=models.ImageField(blank=True, upload_to='communication_pictures/themes/%Y/%m/%d/'),
        ),
    ]
