# Generated by Django 4.1.2 on 2023-01-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
