# Generated by Django 4.1.7 on 2023-05-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_post_author_alter_theme_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=3000, verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='header',
            field=models.TextField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='theme',
            name='text',
            field=models.TextField(max_length=5000),
        ),
    ]
